GET http://localhost:3001/api/persons
# DELETE http://localhost:3001/api/persons/1

# POST http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "Arnold",
#     "number": "305035"
# }

# PUT http://localhost:3001/api/persons/60fbe7d247ac08591b336b53
# Content-Type: application/json

# {
#     "name": "Arnold222",
#     "number": "305035xxxx"
# }